# This is a basic workflow to help you get started with Actions

name: Deploy the cqrs api

# Controls when the workflow will run
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Transfer files to .66 server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME}}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          source: './publish'
          target: '/home/debian'

      # Runs a set of commands using the runners shell
      - name: SSH into .66 server
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.HOST_USERNAME }}
            password: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.SERVER_PORT }}
            script: |
              sudo systemctl restart cqrsapp2.service 
              sudo systemctl restart nginx.service
              

